[build]
  publish = "frontend"
  base = "."

# Custom redirects for each HTML page
[[redirects]]
  from = "/login"
  to = "/views/login.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/views/signup.html"
  status = 200

[[redirects]]
  from = "/login-selection"
  to = "/views/login-selection.html"
  status = 200

[[redirects]]
  from = "/login-handyman"
  to = "/views/login-handyman.html"
  status = 200

[[redirects]]
  from = "/joinHandy"
  to = "/views/joinHandy.html"
  status = 200

[[redirects]]
  from = "/search-handyman"
  to = "/views/search-handyman.html"
  status = 200

[[redirects]]
  from = "/handyman-profile"
  to = "/views/handyman-profile.html"
  status = 200

[[redirects]]
  from = "/booking"
  to = "/views/booking.html"
  status = 200

[[redirects]]
  from = "/customer-dashboard"
  to = "/views/customer-dashboard.html"
  status = 200

[[redirects]]
  from = "/handyman-dashboard"
  to = "/views/handyman-dashboard.html"
  status = 200

[[redirects]]
  from = "/my-handyman-profile"
  to = "/views/my-handyman-profile.html"
  status = 200

[[redirects]]
  from = "/view-handymen"
  to = "/views/view-handymen.html"
  status = 200

[[redirects]]
  from = "/all-home-projects"
  to = "/views/all-home-projects.html"
  status = 200

[[redirects]]
  from = "/debug"
  to = "/views/debug.html"
  status = 200

# Serve static assets from public directory
[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200

# Fallback for SPA-like behavior (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 